version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=pwd4librenms
      - MYSQL_DATABASE=librenms
    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=pwd4librenms
      - TZ=Europe/Berlin
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
    restart: always

  librenms-poller-1:
    build: .
    image: seti/librenms
    container_name: librenms-poller-1
    hostname: librenms-poller-1
    depends_on:
      - librenms
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=pwd4librenms
      - IS_POLLER=1
      - POLLER_GROUP=1
      - MEMCACHED_HOST=librenms
      - MEMCACHED_PORT=11211
      - RRDCACHED=librenms:42217
    restart: always
